// Regenerates the "what this fork adds" block in the top-level README.md from
// features.json. Everything between the FORK-FEATURES markers is overwritten, so edit
// features.json, never the generated block. Fails if a listed screenshot is missing.
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '../..');
const README = path.join(ROOT, 'README.md');
const START = '<!-- FORK-FEATURES:START (generated by tools/screenshots/build-readme.mjs - do not edit by hand) -->';
const END = '<!-- FORK-FEATURES:END -->';
const features = JSON.parse(fs.readFileSync(path.join(import.meta.dirname, 'features.json'), 'utf8'));

const missing = features
	.flatMap((f) => f.screenshots)
	.filter((s) => !fs.existsSync(path.join(ROOT, 'screenshots', s.file)));
if (missing.length) {
	console.error(`Missing screenshots (run tools/screenshots/run.sh): ${missing.map((s) => s.file).join(', ')}`);
	process.exit(1);
}

const bullets = features.map((f) => `- **${f.title}.** ${f.summary}`).join('\n');
const shots = features
	.map((f) => {
		const imgs = f.screenshots
			.map(
				(s) =>
					`<p align="center"><img src="screenshots/${s.file}" alt="${s.caption}" width="720"><br><sub>${s.caption}</sub></p>`
			)
			.join('\n\n');
		return `#### ${f.title}\n\n${imgs}`;
	})
	.join('\n\n');

const block = `${START}
### What this fork adds

${bullets}

### Screenshots

${shots}
${END}`;

const readme = fs.readFileSync(README, 'utf8');
const re = new RegExp(`${START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${END}`);
if (!re.test(readme)) {
	console.error('README.md has no FORK-FEATURES markers; see AGENTS.md.');
	process.exit(1);
}
fs.writeFileSync(README, readme.replace(re, () => block));
console.log('README.md updated');
